name: CI/CD

on: 
    push: 
        branches: 
            - "master"

jobs:
    build:
        runs-on:
            - "ubuntu-latest"
        steps:
            
            - name: "Docker build"
              uses: docker/build-push-action@v5.3.0
              with:
                context: "."
                tags: "go-todo"
                file: "Dockerfile"